/*-------------------------------------------------------------------------
 |                                                                         
 |             SAS SUPPLEMENTAL SYNTAX FILE FOR ICPSR 30103
 |        HOW COUPLES MEET AND STAY TOGETHER (HCMST), WAVE 1 2009,
 |          WAVE 2 2010, WAVE 3 2011, WAVE 4 2013, WAVE 5 2015,
 |                             UNITED STATES
 |                    (DATASET 0001: PUBLIC USE DATA)
 |
 | This SAS program is provided for optional use with the SAS transport
 | version of this data file as distributed by ICPSR. The metadata
 | provided below are not stored in the SAS transport version of this data
 | collection.  Users need to use SAS PROC CIMPORT to import the SAS
 | transport file to a SAS data set on their system. This program can
 | then be used in conjunction with the SAS system data file.
 |
 | DATA:  begins a SAS data step and names an output SAS data set. Users
 | should replace "SAS-dataset" with their name for the SAS data set copied
 | from the SAS transport file. Users can add a SAS libname statement
 | and an output SAS data set name to make a permanent SAS data set.
 |
 | MISSING VALUE RECODES:  sets user-defined numeric missing values to
 | missing as interpreted by the SAS system. Only variables with
 | user-defined missing values are included in this section.
 |
 | If any variables have more than one missing value, they are assigned
 | to the standard missing value of a single period (.) in the statement
 | below. To maintain the original meaning of missing codes, users may want
 | to take advantage of the SAS missing values (the letters A-Z or an
 | underscore preceded by a period).
 |
 | An example of a standard missing value recode:
 |
 |   IF (RELATION = 98 OR RELATION = 99) THEN RELATION = .;
 |
 | The same example using special missing value recodes:
 |
 |    IF RELATION = 98 THEN RELATION = .A;
 |    IF RELATION = 99 THEN RELATION = .B;
 |
 | NOTE:  Users should modify this file to suit their specific needs.
 | The MISSING VALUE RECODES section has been commented out (i.e., '/*').
 | To make this section active in the program, users should remove the SAS
 | comment indicators from this section.
 |
 |------------------------------------------------------------------------*/


* SAS DATA STEP;
DATA;
SET SAS-dataset ;


* USER-DEFINED MISSING VALUES RECODE TO SAS SYSMIS;

/*
   IF (PPAGE = -1 OR PPAGE = -2) THEN PPAGE = .;
   IF (PPEDUC = -1 OR PPEDUC = -2) THEN PPEDUC = .;
   IF (PPEDUCAT = -1 OR PPEDUCAT = -2) THEN PPEDUCAT = .;
   IF (PPETHM = -1 OR PPETHM = -2) THEN PPETHM = .;
   IF (PPGENDER = -1 OR PPGENDER = -2) THEN PPGENDER = .;
   IF (PPHHHEAD = -1 OR PPHHHEAD = -2) THEN PPHHHEAD = .;
   IF (PPHOUSE = -1 OR PPHOUSE = -2) THEN PPHOUSE = .;
   IF (PPINCIMP = -1 OR PPINCIMP = -2) THEN PPINCIMP = .;
   IF (PPMARIT = -1 OR PPMARIT = -2) THEN PPMARIT = .;
   IF (PPMSACAT = -1 OR PPMSACAT = -2) THEN PPMSACAT = .;
   IF (PPREG4 = -1 OR PPREG4 = -2) THEN PPREG4 = .;
   IF (PPRENT = -1 OR PPRENT = -2) THEN PPRENT = .;
   IF (PPT01 = -1 OR PPT01 = -2) THEN PPT01 = .;
   IF (PPT1317 = -1 OR PPT1317 = -2) THEN PPT1317 = .;
   IF (PPT18OV = -1 OR PPT18OV = -2) THEN PPT18OV = .;
   IF (PPT25 = -1 OR PPT25 = -2) THEN PPT25 = .;
   IF (PPT612 = -1 OR PPT612 = -2) THEN PPT612 = .;
   IF (PPWORK = -1 OR PPWORK = -2) THEN PPWORK = .;
   IF (PPQ14ARACE = -1 OR PPQ14ARACE = -2) THEN PPQ14ARACE = .;
   IF (PPHISPAN = -1 OR PPHISPAN = -2) THEN PPHISPAN = .;
   IF (PPRACE_WHITE = -1 OR PPRACE_WHITE = -2) THEN PPRACE_WHITE = .;
   IF (PPRACE_BLACK = -1 OR PPRACE_BLACK = -2) THEN PPRACE_BLACK = .;
   IF (PPRACE_NATIVEAMERICAN = -1 OR PPRACE_NATIVEAMERICAN = -2) THEN PPRACE_NATIVEAMERICAN = .;
   IF (PPRACE_ASIANINDIAN = -1 OR PPRACE_ASIANINDIAN = -2) THEN PPRACE_ASIANINDIAN = .;
   IF (PPRACE_CHINESE = -1 OR PPRACE_CHINESE = -2) THEN PPRACE_CHINESE = .;
   IF (PPRACE_FILIPINO = -1 OR PPRACE_FILIPINO = -2) THEN PPRACE_FILIPINO = .;
   IF (PPRACE_JAPANESE = -1 OR PPRACE_JAPANESE = -2) THEN PPRACE_JAPANESE = .;
   IF (PPRACE_KOREAN = -1 OR PPRACE_KOREAN = -2) THEN PPRACE_KOREAN = .;
   IF (PPRACE_VIETNAMESE = -1 OR PPRACE_VIETNAMESE = -2) THEN PPRACE_VIETNAMESE = .;
   IF (PPRACE_OTHERASIAN = -1 OR PPRACE_OTHERASIAN = -2) THEN PPRACE_OTHERASIAN = .;
   IF (PPRACE_HAWAIIAN = -1 OR PPRACE_HAWAIIAN = -2) THEN PPRACE_HAWAIIAN = .;
   IF (PPRACE_GUAMANIAN = -1 OR PPRACE_GUAMANIAN = -2) THEN PPRACE_GUAMANIAN = .;
   IF (PPRACE_SAMOAN = -1 OR PPRACE_SAMOAN = -2) THEN PPRACE_SAMOAN = .;
   IF (PPRACE_OTHERPACIFICISLANDER = -1 OR PPRACE_OTHERPACIFICISLANDER = -2) THEN PPRACE_OTHERPACIFICISLANDER = .;
   IF (PPRACE_SOMEOTHERRACE = -1 OR PPRACE_SOMEOTHERRACE = -2) THEN PPRACE_SOMEOTHERRACE = .;
   IF (PAPGLB_FRIEND = -1 OR PAPGLB_FRIEND = -2) THEN PAPGLB_FRIEND = .;
   IF (PPPARTYID3 = -1 OR PPPARTYID3 = -2) THEN PPPARTYID3 = .;
   IF (PAPEVANGELICAL = -1 OR PAPEVANGELICAL = -2) THEN PAPEVANGELICAL = .;
   IF (PAPRELIGION = -1 OR PAPRELIGION = -2) THEN PAPRELIGION = .;
   IF (PPHHCOMP11_MEMBER2_GENDER = -1) THEN PPHHCOMP11_MEMBER2_GENDER = .;
   IF (PPHHCOMP11_MEMBER3_GENDER = -1) THEN PPHHCOMP11_MEMBER3_GENDER = .;
   IF (PPHHCOMP11_MEMBER4_GENDER = -1) THEN PPHHCOMP11_MEMBER4_GENDER = .;
   IF (PPHHCOMP11_MEMBER5_GENDER = -1) THEN PPHHCOMP11_MEMBER5_GENDER = .;
   IF (PPHHCOMP11_MEMBER6_GENDER = -1) THEN PPHHCOMP11_MEMBER6_GENDER = .;
   IF (PPHHCOMP11_MEMBER7_GENDER = -1) THEN PPHHCOMP11_MEMBER7_GENDER = .;
   IF (PPHHCOMP11_MEMBER8_GENDER = -1) THEN PPHHCOMP11_MEMBER8_GENDER = .;
   IF (PPHHCOMP11_MEMBER9_GENDER = -1) THEN PPHHCOMP11_MEMBER9_GENDER = .;
   IF (PPHHCOMP11_MEMBER10_GENDER = -1) THEN PPHHCOMP11_MEMBER10_GENDER = .;
   IF (PPHHCOMP11_MEMBER11_GENDER = -1) THEN PPHHCOMP11_MEMBER11_GENDER = .;
   IF (PPHHCOMP11_MEMBER12_GENDER = -1) THEN PPHHCOMP11_MEMBER12_GENDER = .;
   IF (PPHHCOMP11_MEMBER13_GENDER = -1) THEN PPHHCOMP11_MEMBER13_GENDER = .;
   IF (PPHHCOMP11_MEMBER14_GENDER = -1) THEN PPHHCOMP11_MEMBER14_GENDER = .;
   IF (PPHHCOMP11_MEMBER15_GENDER = -1) THEN PPHHCOMP11_MEMBER15_GENDER = .;
   IF (PPHHCOMP11_MEMBER2_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER2_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER3_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER3_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER4_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER4_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER5_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER5_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER6_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER6_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER7_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER7_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER8_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER8_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER9_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER9_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER10_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER10_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER11_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER11_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER12_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER12_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER13_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER13_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER14_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER14_RELATIONSHIP = .;
   IF (PPHHCOMP11_MEMBER15_RELATIONSHIP = -1) THEN PPHHCOMP11_MEMBER15_RELATIONSHIP = .;
   IF (IRB_CONSENT = -1) THEN IRB_CONSENT = .;
   IF (PAPGLB_STATUS = -1 OR PAPGLB_STATUS = -2) THEN PAPGLB_STATUS = .;
   IF (S1 = -1) THEN S1 = .;
   IF (S1A = -1) THEN S1A = .;
   IF (S2 = -1) THEN S2 = .;
   IF (Q3_CODES = -1) THEN Q3_CODES = .;
   IF (Q4 = -1) THEN Q4 = .;
   IF (Q5 = -1) THEN Q5 = .;
   IF (Q6A = -1) THEN Q6A = .;
   IF (Q6B = -1) THEN Q6B = .;
   IF (Q7A = -1) THEN Q7A = .;
   IF (Q7B = -1) THEN Q7B = .;
   IF (Q8A = -1) THEN Q8A = .;
   IF (Q8B = -1) THEN Q8B = .;
   IF (Q10 = -1) THEN Q10 = .;
   IF (Q11 = -1) THEN Q11 = .;
   IF (Q12 = -1) THEN Q12 = .;
   IF (Q13A = -1) THEN Q13A = .;
   IF (Q13B = -1) THEN Q13B = .;
   IF (Q14 = -1) THEN Q14 = .;
   IF (Q15A1_COMPRESSED = -1) THEN Q15A1_COMPRESSED = .;
   IF (Q16 = -1) THEN Q16 = .;
   IF (Q17A = -1) THEN Q17A = .;
   IF (Q17B = -1) THEN Q17B = .;
   IF (Q17C = -1) THEN Q17C = .;
   IF (Q17D = -1) THEN Q17D = .;
   IF (Q18A_1 = -1) THEN Q18A_1 = .;
   IF (Q18A_2 = -1) THEN Q18A_2 = .;
   IF (Q18A_3 = -1) THEN Q18A_3 = .;
   IF (Q18B_CODES = -1) THEN Q18B_CODES = .;
   IF (Q18C_CODES = -1) THEN Q18C_CODES = .;
   IF (Q19 = -1) THEN Q19 = .;
   IF (Q20 = -1) THEN Q20 = .;
   IF (Q22 = -1) THEN Q22 = .;
   IF (Q23 = -1) THEN Q23 = .;
   IF (Q24_CODES = -1) THEN Q24_CODES = .;
   IF (Q25 = -1) THEN Q25 = .;
   IF (Q26 = -1) THEN Q26 = .;
   IF (Q27 = -1) THEN Q27 = .;
   IF (Q28 = -1) THEN Q28 = .;
   IF (Q29 = -1) THEN Q29 = .;
   IF (Q30 = -1) THEN Q30 = .;
   IF (Q31_1 = -1) THEN Q31_1 = .;
   IF (Q31_2 = -1) THEN Q31_2 = .;
   IF (Q31_3 = -1) THEN Q31_3 = .;
   IF (Q31_4 = -1) THEN Q31_4 = .;
   IF (Q31_5 = -1) THEN Q31_5 = .;
   IF (Q31_6 = -1) THEN Q31_6 = .;
   IF (Q31_7 = -1) THEN Q31_7 = .;
   IF (Q31_8 = -1) THEN Q31_8 = .;
   IF (Q31_9 = -1) THEN Q31_9 = .;
   IF (Q32 = -1) THEN Q32 = .;
   IF (Q33_1 = -1) THEN Q33_1 = .;
   IF (Q33_2 = -1) THEN Q33_2 = .;
   IF (Q33_3 = -1) THEN Q33_3 = .;
   IF (Q33_4 = -1) THEN Q33_4 = .;
   IF (Q33_5 = -1) THEN Q33_5 = .;
   IF (Q33_6 = -1) THEN Q33_6 = .;
   IF (Q33_7 = -1) THEN Q33_7 = .;
   IF (Q34 = -1) THEN Q34 = .;
   IF (Q35_CODES = -1) THEN Q35_CODES = .;
   IF (PARTNER_RELIGION_RECLASSIFIED = -1) THEN PARTNER_RELIGION_RECLASSIFIED = .;
   IF (PARTNER_RELIGION_CHILD_RECLASS = -1) THEN PARTNER_RELIGION_CHILD_RECLASS = .;
   IF (OWN_RELIGION_CHILD_RECLASS = -1) THEN OWN_RELIGION_CHILD_RECLASS = .;
   IF (EITHER_INTERNET_ADJUSTED = -1) THEN EITHER_INTERNET_ADJUSTED = .;
   IF (POTENTIAL_PARTNER_GENDER_RECODES = -1) THEN POTENTIAL_PARTNER_GENDER_RECODES = .;
   IF (ALT_PARTNER_GENDER = -1) THEN ALT_PARTNER_GENDER = .;
   IF (RESPONDENT_RELIGION_AT_16 = -1) THEN RESPONDENT_RELIGION_AT_16 = .;
   IF (PARTNER_RELIGION_AT_16 = -1) THEN PARTNER_RELIGION_AT_16 = .;
   IF (HOME_COUNTRY_RECODE = -1) THEN HOME_COUNTRY_RECODE = .;
   IF (PP2_PPHHHEAD = -1 OR PP2_PPHHHEAD = -2) THEN PP2_PPHHHEAD = .;
   IF (PP2_PPHHSIZE = -1 OR PP2_PPHHSIZE = -2) THEN PP2_PPHHSIZE = .;
   IF (PP2_PPHOUSE = -1 OR PP2_PPHOUSE = -2) THEN PP2_PPHOUSE = .;
   IF (PP2_PPINCIMP = -1 OR PP2_PPINCIMP = -2) THEN PP2_PPINCIMP = .;
   IF (PP2_PPMARIT = -1 OR PP2_PPMARIT = -2) THEN PP2_PPMARIT = .;
   IF (PP2_PPMSACAT = -1 OR PP2_PPMSACAT = -2) THEN PP2_PPMSACAT = .;
   IF (PP2_PPEDUC = -1 OR PP2_PPEDUC = -2) THEN PP2_PPEDUC = .;
   IF (PP2_PPEDUCAT = -1 OR PP2_PPEDUCAT = -2) THEN PP2_PPEDUCAT = .;
   IF (PP2_PPETHM = -1 OR PP2_PPETHM = -2) THEN PP2_PPETHM = .;
   IF (PP2_PPREG4 = -1 OR PP2_PPREG4 = -2) THEN PP2_PPREG4 = .;
   IF (PP2_PPRENT = -1 OR PP2_PPRENT = -2) THEN PP2_PPRENT = .;
   IF (PP2_PPT01 = -1 OR PP2_PPT01 = -2) THEN PP2_PPT01 = .;
   IF (PP2_PPT1317 = -1 OR PP2_PPT1317 = -2) THEN PP2_PPT1317 = .;
   IF (PP2_PPT18OV = -1 OR PP2_PPT18OV = -2) THEN PP2_PPT18OV = .;
   IF (PP2_PPT25 = -1 OR PP2_PPT25 = -2) THEN PP2_PPT25 = .;
   IF (PP2_PPT612 = -1 OR PP2_PPT612 = -2) THEN PP2_PPT612 = .;
   IF (PP2_PPWORK = -1 OR PP2_PPWORK = -2) THEN PP2_PPWORK = .;
   IF (W2_Q1 = -1) THEN W2_Q1 = .;
   IF (W2_Q2 = -1) THEN W2_Q2 = .;
   IF (W2_Q3 = -1) THEN W2_Q3 = .;
   IF (W2_Q4 = -1) THEN W2_Q4 = .;
   IF (W2_Q5 = -1) THEN W2_Q5 = .;
   IF (W2_Q6 = -1) THEN W2_Q6 = .;
   IF (W2_Q7 = -1) THEN W2_Q7 = .;
   IF (W2_Q8 = -1) THEN W2_Q8 = .;
   IF (W2_Q9 = -1) THEN W2_Q9 = .;
   IF (W2_Q10 = -1) THEN W2_Q10 = .;
   IF (PP3_PPHHHEAD = -1 OR PP3_PPHHHEAD = -2) THEN PP3_PPHHHEAD = .;
   IF (PP3_PPHHSIZE = -1 OR PP3_PPHHSIZE = -2) THEN PP3_PPHHSIZE = .;
   IF (PP3_PPHOUSE = -1 OR PP3_PPHOUSE = -2) THEN PP3_PPHOUSE = .;
   IF (PP3_PPINCIMP = -1 OR PP3_PPINCIMP = -2) THEN PP3_PPINCIMP = .;
   IF (PP3_PPMARIT = -1 OR PP3_PPMARIT = -2) THEN PP3_PPMARIT = .;
   IF (PP3_PPMSACAT = -1 OR PP3_PPMSACAT = -2) THEN PP3_PPMSACAT = .;
   IF (PP3_PPRENT = -1 OR PP3_PPRENT = -2) THEN PP3_PPRENT = .;
   IF (PP3_PPREG4 = -1 OR PP3_PPREG4 = -2) THEN PP3_PPREG4 = .;
   IF (PP3_PPT01 = -1 OR PP3_PPT01 = -2) THEN PP3_PPT01 = .;
   IF (PP3_PPT1317 = -1 OR PP3_PPT1317 = -2) THEN PP3_PPT1317 = .;
   IF (PP3_PPT18OV = -1 OR PP3_PPT18OV = -2) THEN PP3_PPT18OV = .;
   IF (PP3_PPT25 = -1 OR PP3_PPT25 = -2) THEN PP3_PPT25 = .;
   IF (PP3_PPT612 = -1 OR PP3_PPT612 = -2) THEN PP3_PPT612 = .;
   IF (PP3_PPWORK = -1 OR PP3_PPWORK = -2) THEN PP3_PPWORK = .;
   IF (PP3_PPEDUC = -1 OR PP3_PPEDUC = -2) THEN PP3_PPEDUC = .;
   IF (PP3_PPEDUCAT = -1 OR PP3_PPEDUCAT = -2) THEN PP3_PPEDUCAT = .;
   IF (PP3_PPETHM = -1 OR PP3_PPETHM = -2) THEN PP3_PPETHM = .;
   IF (W3_Q1 = -1) THEN W3_Q1 = .;
   IF (W3_Q2 = -1) THEN W3_Q2 = .;
   IF (W3_Q3 = -1) THEN W3_Q3 = .;
   IF (W3_Q4 = -1) THEN W3_Q4 = .;
   IF (W3_MBTIMING_YEAR = -1) THEN W3_MBTIMING_YEAR = .;
   IF (W3_Q5 = -1) THEN W3_Q5 = .;
   IF (W3_Q6 = -1) THEN W3_Q6 = .;
   IF (W3_Q7 = -1) THEN W3_Q7 = .;
   IF (W3_Q8 = -1) THEN W3_Q8 = .;
   IF (W3_Q9 = -1) THEN W3_Q9 = .;
   IF (W3_Q10 = -1) THEN W3_Q10 = .;
   IF (W3_NONMBTIMING_YEAR = -1) THEN W3_NONMBTIMING_YEAR = .;
   IF (Q15A1 = -1) THEN Q15A1 = .;
   IF (W4_Q1 = -1) THEN W4_Q1 = .;
   IF (W4_Q2 = -1) THEN W4_Q2 = .;
   IF (W4_QUALITY = -1) THEN W4_QUALITY = .;
   IF (W4_ATTRACTIVE = -1) THEN W4_ATTRACTIVE = .;
   IF (W4_ATTRACTIVE_PARTNER = -1) THEN W4_ATTRACTIVE_PARTNER = .;
   IF (W4_Q3 = -1) THEN W4_Q3 = .;
   IF (W4_Q4 = -1) THEN W4_Q4 = .;
   IF (W4_Q7 = -1) THEN W4_Q7 = .;
   IF (W4_Q8_A = -1) THEN W4_Q8_A = .;
   IF (W4_Q8_B = -1) THEN W4_Q8_B = .;
   IF (W4_Q9 = -1) THEN W4_Q9 = .;
   IF (W4_Q10 = -1) THEN W4_Q10 = .;
   IF (PP4_PPEDUC = -1 OR PP4_PPEDUC = -2) THEN PP4_PPEDUC = .;
   IF (PP4_PPEDUCAT = -1 OR PP4_PPEDUCAT = -2) THEN PP4_PPEDUCAT = .;
   IF (PP4_PPETHM = -1 OR PP4_PPETHM = -2) THEN PP4_PPETHM = .;
   IF (PP4_PPHHHEAD = -1 OR PP4_PPHHHEAD = -2) THEN PP4_PPHHHEAD = .;
   IF (PP4_PPHHSIZE = -1 OR PP4_PPHHSIZE = -2) THEN PP4_PPHHSIZE = .;
   IF (PP4_PPHOUSE = -1 OR PP4_PPHOUSE = -2) THEN PP4_PPHOUSE = .;
   IF (PP4_PPINCIMP = -1 OR PP4_PPINCIMP = -2) THEN PP4_PPINCIMP = .;
   IF (PP4_PPMARIT = -1 OR PP4_PPMARIT = -2) THEN PP4_PPMARIT = .;
   IF (PP4_PPMSACAT = -1 OR PP4_PPMSACAT = -2) THEN PP4_PPMSACAT = .;
   IF (PP4_PPREG4 = -1 OR PP4_PPREG4 = -2) THEN PP4_PPREG4 = .;
   IF (PP4_PPRENT = -1 OR PP4_PPRENT = -2) THEN PP4_PPRENT = .;
   IF (PP4_PPT01 = -1 OR PP4_PPT01 = -2) THEN PP4_PPT01 = .;
   IF (PP4_PPT25 = -1 OR PP4_PPT25 = -2) THEN PP4_PPT25 = .;
   IF (PP4_PPT612 = -1 OR PP4_PPT612 = -2) THEN PP4_PPT612 = .;
   IF (PP4_PPT1317 = -1 OR PP4_PPT1317 = -2) THEN PP4_PPT1317 = .;
   IF (PP4_PPT18OV = -1 OR PP4_PPT18OV = -2) THEN PP4_PPT18OV = .;
   IF (PP4_PPWORK = -1 OR PP4_PPWORK = -2) THEN PP4_PPWORK = .;
   IF (PPA2009_HOW_OFTEN_SERVICES = -1 OR PPA2009_HOW_OFTEN_SERVICES = -2) THEN PPA2009_HOW_OFTEN_SERVICES = .;
   IF (W5_Q1 = -1) THEN W5_Q1 = .;
   IF (W5_Q2 = -1) THEN W5_Q2 = .;
   IF (W5_SEX_FREQUENCY = -1) THEN W5_SEX_FREQUENCY = .;
   IF (W5_P_MONOGAMY = -1) THEN W5_P_MONOGAMY = .;
   IF (W5_IDENTITY = -1) THEN W5_IDENTITY = .;
   IF (W5_OUTNESS = -1) THEN W5_OUTNESS = .;
   IF (W5_Q3 = -1) THEN W5_Q3 = .;
   IF (W5_Q4 = -1) THEN W5_Q4 = .;
   IF (W5_MBTIMING_MONTH = -1) THEN W5_MBTIMING_MONTH = .;
   IF (W5_Q5 = -1) THEN W5_Q5 = .;
   IF (W5_Q6 = -1) THEN W5_Q6 = .;
   IF (W5_Q7 = -1) THEN W5_Q7 = .;
   IF (W5_MAR_MONTH = -1) THEN W5_MAR_MONTH = .;
   IF (W5_Q8 = -1) THEN W5_Q8 = .;
   IF (W5_CIV_YEAR = -1) THEN W5_CIV_YEAR = .;
   IF (W5_CIV_MONTH = -1) THEN W5_CIV_MONTH = .;
   IF (W5_Q9 = -1) THEN W5_Q9 = .;
   IF (W5_Q10 = -1) THEN W5_Q10 = .;
   IF (W5_NONMBTIMING_MONTH = -1) THEN W5_NONMBTIMING_MONTH = .;
   IF (PP5_PPAGE = -2 OR PP5_PPAGE = -1) THEN PP5_PPAGE = .;
   IF (PP5_PPEDUC = -2 OR PP5_PPEDUC = -1) THEN PP5_PPEDUC = .;
   IF (PP5_PPEDUCAT = -2 OR PP5_PPEDUCAT = -1) THEN PP5_PPEDUCAT = .;
   IF (PP5_PPETHM = -2 OR PP5_PPETHM = -1) THEN PP5_PPETHM = .;
   IF (PP5_PPGENDER = -2 OR PP5_PPGENDER = -1) THEN PP5_PPGENDER = .;
   IF (PP5_PPHHSIZE = -2 OR PP5_PPHHSIZE = -1) THEN PP5_PPHHSIZE = .;
   IF (PP5_PPHOUSE = -2 OR PP5_PPHOUSE = -1) THEN PP5_PPHOUSE = .;
   IF (PP5_PPINCIMP = -2 OR PP5_PPINCIMP = -1) THEN PP5_PPINCIMP = .;
   IF (PP5_PPMARIT = -2 OR PP5_PPMARIT = -1) THEN PP5_PPMARIT = .;
   IF (PP5_PPREG4 = -2 OR PP5_PPREG4 = -1) THEN PP5_PPREG4 = .;
   IF (PP5_PPT01 = -2 OR PP5_PPT01 = -1) THEN PP5_PPT01 = .;
   IF (PP5_PPT612 = -2 OR PP5_PPT612 = -1) THEN PP5_PPT612 = .;
   IF (PP5_PPT1317 = -2 OR PP5_PPT1317 = -1) THEN PP5_PPT1317 = .;
   IF (PP5_PPT18OV = -2 OR PP5_PPT18OV = -1) THEN PP5_PPT18OV = .;
   IF (PP5_PPWORK = -2 OR PP5_PPWORK = -1) THEN PP5_PPWORK = .;
   IF (PPMARIT_2014 = -2 OR PPMARIT_2014 = -1) THEN PPMARIT_2014 = .;
   IF (PPMARIT_2013 = -2 OR PPMARIT_2013 = -1) THEN PPMARIT_2013 = .;
   IF (PPMARIT_2012 = -2 OR PPMARIT_2012 = -1) THEN PPMARIT_2012 = .;
   IF (PPMARIT_2011 = -2 OR PPMARIT_2011 = -1) THEN PPMARIT_2011 = .;
   IF (PPMARIT_2010 = -2 OR PPMARIT_2010 = -1) THEN PPMARIT_2010 = .;
   IF (PPMARIT_2009 = -2 OR PPMARIT_2009 = -1) THEN PPMARIT_2009 = .;
   IF (PPMARIT_2007 = -2 OR PPMARIT_2007 = -1) THEN PPMARIT_2007 = .;
*/

RUN ;
