/*-------------------------------------------------------------------------*
 |                                                                         
 |            STATA SUPPLEMENTAL SYNTAX FILE FOR ICPSR 30103
 |        HOW COUPLES MEET AND STAY TOGETHER (HCMST), WAVE 1 2009,
 |          WAVE 2 2010, WAVE 3 2011, WAVE 4 2013, WAVE 5 2015,
 |                             UNITED STATES
 |                    (DATASET 0001: PUBLIC USE DATA)
 |
 |
 | This Stata missing value recode program is provided for optional use with
 | the Stata system version of this data file as distributed by ICPSR.
 | The program replaces user-defined numeric missing values (e.g., -9)
 | with generic system missing "."  Note that Stata allows you to specify
 | up to 27 unique missing value codes.  Only variables with user-defined
 | missing values are included in this program.
 |
 | To apply the missing value recodes, users need to first open the
 | Stata data file on their system, apply the missing value recodes if
 | desired, then save a new copy of the data file with the missing values
 | applied.  Users are strongly advised to use a different filename when
 | saving the new file.
 |
 *------------------------------------------------------------------------*/

replace PPAGE = . if (PPAGE == -1 | PPAGE == -2)
replace PPEDUC = . if (PPEDUC == -1 | PPEDUC == -2)
replace PPEDUCAT = . if (PPEDUCAT == -1 | PPEDUCAT == -2)
replace PPETHM = . if (PPETHM == -1 | PPETHM == -2)
replace PPGENDER = . if (PPGENDER == -1 | PPGENDER == -2)
replace PPHHHEAD = . if (PPHHHEAD == -1 | PPHHHEAD == -2)
replace PPHOUSE = . if (PPHOUSE == -1 | PPHOUSE == -2)
replace PPINCIMP = . if (PPINCIMP == -1 | PPINCIMP == -2)
replace PPMARIT = . if (PPMARIT == -1 | PPMARIT == -2)
replace PPMSACAT = . if (PPMSACAT == -1 | PPMSACAT == -2)
replace PPREG4 = . if (PPREG4 == -1 | PPREG4 == -2)
replace PPRENT = . if (PPRENT == -1 | PPRENT == -2)
replace PPT01 = . if (PPT01 == -1 | PPT01 == -2)
replace PPT1317 = . if (PPT1317 == -1 | PPT1317 == -2)
replace PPT18OV = . if (PPT18OV == -1 | PPT18OV == -2)
replace PPT25 = . if (PPT25 == -1 | PPT25 == -2)
replace PPT612 = . if (PPT612 == -1 | PPT612 == -2)
replace PPWORK = . if (PPWORK == -1 | PPWORK == -2)
replace PPQ14ARACE = . if (PPQ14ARACE == -1 | PPQ14ARACE == -2)
replace PPHISPAN = . if (PPHISPAN == -1 | PPHISPAN == -2)
replace PPRACE_WHITE = . if (PPRACE_WHITE == -1 | PPRACE_WHITE == -2)
replace PPRACE_BLACK = . if (PPRACE_BLACK == -1 | PPRACE_BLACK == -2)
replace PPRACE_NATIVEAMERICAN = . if (PPRACE_NATIVEAMERICAN == -1 | PPRACE_NATIVEAMERICAN == -2)
replace PPRACE_ASIANINDIAN = . if (PPRACE_ASIANINDIAN == -1 | PPRACE_ASIANINDIAN == -2)
replace PPRACE_CHINESE = . if (PPRACE_CHINESE == -1 | PPRACE_CHINESE == -2)
replace PPRACE_FILIPINO = . if (PPRACE_FILIPINO == -1 | PPRACE_FILIPINO == -2)
replace PPRACE_JAPANESE = . if (PPRACE_JAPANESE == -1 | PPRACE_JAPANESE == -2)
replace PPRACE_KOREAN = . if (PPRACE_KOREAN == -1 | PPRACE_KOREAN == -2)
replace PPRACE_VIETNAMESE = . if (PPRACE_VIETNAMESE == -1 | PPRACE_VIETNAMESE == -2)
replace PPRACE_OTHERASIAN = . if (PPRACE_OTHERASIAN == -1 | PPRACE_OTHERASIAN == -2)
replace PPRACE_HAWAIIAN = . if (PPRACE_HAWAIIAN == -1 | PPRACE_HAWAIIAN == -2)
replace PPRACE_GUAMANIAN = . if (PPRACE_GUAMANIAN == -1 | PPRACE_GUAMANIAN == -2)
replace PPRACE_SAMOAN = . if (PPRACE_SAMOAN == -1 | PPRACE_SAMOAN == -2)
replace PPRACE_OTHERPACIFICISLANDER = . if (PPRACE_OTHERPACIFICISLANDER == -1 | PPRACE_OTHERPACIFICISLANDER == -2)
replace PPRACE_SOMEOTHERRACE = . if (PPRACE_SOMEOTHERRACE == -1 | PPRACE_SOMEOTHERRACE == -2)
replace PAPGLB_FRIEND = . if (PAPGLB_FRIEND == -1 | PAPGLB_FRIEND == -2)
replace PPPARTYID3 = . if (PPPARTYID3 == -1 | PPPARTYID3 == -2)
replace PAPEVANGELICAL = . if (PAPEVANGELICAL == -1 | PAPEVANGELICAL == -2)
replace PAPRELIGION = . if (PAPRELIGION == -1 | PAPRELIGION == -2)
replace PPHHCOMP11_MEMBER2_GENDER = . if (PPHHCOMP11_MEMBER2_GENDER == -1)
replace PPHHCOMP11_MEMBER3_GENDER = . if (PPHHCOMP11_MEMBER3_GENDER == -1)
replace PPHHCOMP11_MEMBER4_GENDER = . if (PPHHCOMP11_MEMBER4_GENDER == -1)
replace PPHHCOMP11_MEMBER5_GENDER = . if (PPHHCOMP11_MEMBER5_GENDER == -1)
replace PPHHCOMP11_MEMBER6_GENDER = . if (PPHHCOMP11_MEMBER6_GENDER == -1)
replace PPHHCOMP11_MEMBER7_GENDER = . if (PPHHCOMP11_MEMBER7_GENDER == -1)
replace PPHHCOMP11_MEMBER8_GENDER = . if (PPHHCOMP11_MEMBER8_GENDER == -1)
replace PPHHCOMP11_MEMBER9_GENDER = . if (PPHHCOMP11_MEMBER9_GENDER == -1)
replace PPHHCOMP11_MEMBER10_GENDER = . if (PPHHCOMP11_MEMBER10_GENDER == -1)
replace PPHHCOMP11_MEMBER11_GENDER = . if (PPHHCOMP11_MEMBER11_GENDER == -1)
replace PPHHCOMP11_MEMBER12_GENDER = . if (PPHHCOMP11_MEMBER12_GENDER == -1)
replace PPHHCOMP11_MEMBER13_GENDER = . if (PPHHCOMP11_MEMBER13_GENDER == -1)
replace PPHHCOMP11_MEMBER14_GENDER = . if (PPHHCOMP11_MEMBER14_GENDER == -1)
replace PPHHCOMP11_MEMBER15_GENDER = . if (PPHHCOMP11_MEMBER15_GENDER == -1)
replace PPHHCOMP11_MEMBER2_RELATIONSHIP = . if (PPHHCOMP11_MEMBER2_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER3_RELATIONSHIP = . if (PPHHCOMP11_MEMBER3_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER4_RELATIONSHIP = . if (PPHHCOMP11_MEMBER4_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER5_RELATIONSHIP = . if (PPHHCOMP11_MEMBER5_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER6_RELATIONSHIP = . if (PPHHCOMP11_MEMBER6_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER7_RELATIONSHIP = . if (PPHHCOMP11_MEMBER7_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER8_RELATIONSHIP = . if (PPHHCOMP11_MEMBER8_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER9_RELATIONSHIP = . if (PPHHCOMP11_MEMBER9_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER10_RELATIONSHIP = . if (PPHHCOMP11_MEMBER10_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER11_RELATIONSHIP = . if (PPHHCOMP11_MEMBER11_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER12_RELATIONSHIP = . if (PPHHCOMP11_MEMBER12_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER13_RELATIONSHIP = . if (PPHHCOMP11_MEMBER13_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER14_RELATIONSHIP = . if (PPHHCOMP11_MEMBER14_RELATIONSHIP == -1)
replace PPHHCOMP11_MEMBER15_RELATIONSHIP = . if (PPHHCOMP11_MEMBER15_RELATIONSHIP == -1)
replace IRB_CONSENT = . if (IRB_CONSENT == -1)
replace PAPGLB_STATUS = . if (PAPGLB_STATUS == -1 | PAPGLB_STATUS == -2)
replace S1 = . if (S1 == -1)
replace S1A = . if (S1A == -1)
replace S2 = . if (S2 == -1)
replace Q3_CODES = . if (Q3_CODES == -1)
replace Q4 = . if (Q4 == -1)
replace Q5 = . if (Q5 == -1)
replace Q6A = . if (Q6A == -1)
replace Q6B = . if (Q6B == -1)
replace Q7A = . if (Q7A == -1)
replace Q7B = . if (Q7B == -1)
replace Q8A = . if (Q8A == -1)
replace Q8B = . if (Q8B == -1)
replace Q10 = . if (Q10 == -1)
replace Q11 = . if (Q11 == -1)
replace Q12 = . if (Q12 == -1)
replace Q13A = . if (Q13A == -1)
replace Q13B = . if (Q13B == -1)
replace Q14 = . if (Q14 == -1)
replace Q15A1_COMPRESSED = . if (Q15A1_COMPRESSED == -1)
replace Q16 = . if (Q16 == -1)
replace Q17A = . if (Q17A == -1)
replace Q17B = . if (Q17B == -1)
replace Q17C = . if (Q17C == -1)
replace Q17D = . if (Q17D == -1)
replace Q18A_1 = . if (Q18A_1 == -1)
replace Q18A_2 = . if (Q18A_2 == -1)
replace Q18A_3 = . if (Q18A_3 == -1)
replace Q18B_CODES = . if (Q18B_CODES == -1)
replace Q18C_CODES = . if (Q18C_CODES == -1)
replace Q19 = . if (Q19 == -1)
replace Q20 = . if (Q20 == -1)
replace Q22 = . if (Q22 == -1)
replace Q23 = . if (Q23 == -1)
replace Q24_CODES = . if (Q24_CODES == -1)
replace Q25 = . if (Q25 == -1)
replace Q26 = . if (Q26 == -1)
replace Q27 = . if (Q27 == -1)
replace Q28 = . if (Q28 == -1)
replace Q29 = . if (Q29 == -1)
replace Q30 = . if (Q30 == -1)
replace Q31_1 = . if (Q31_1 == -1)
replace Q31_2 = . if (Q31_2 == -1)
replace Q31_3 = . if (Q31_3 == -1)
replace Q31_4 = . if (Q31_4 == -1)
replace Q31_5 = . if (Q31_5 == -1)
replace Q31_6 = . if (Q31_6 == -1)
replace Q31_7 = . if (Q31_7 == -1)
replace Q31_8 = . if (Q31_8 == -1)
replace Q31_9 = . if (Q31_9 == -1)
replace Q32 = . if (Q32 == -1)
replace Q33_1 = . if (Q33_1 == -1)
replace Q33_2 = . if (Q33_2 == -1)
replace Q33_3 = . if (Q33_3 == -1)
replace Q33_4 = . if (Q33_4 == -1)
replace Q33_5 = . if (Q33_5 == -1)
replace Q33_6 = . if (Q33_6 == -1)
replace Q33_7 = . if (Q33_7 == -1)
replace Q34 = . if (Q34 == -1)
replace Q35_CODES = . if (Q35_CODES == -1)
replace PARTNER_RELIGION_RECLASSIFIED = . if (PARTNER_RELIGION_RECLASSIFIED == -1)
replace PARTNER_RELIGION_CHILD_RECLASS = . if (PARTNER_RELIGION_CHILD_RECLASS == -1)
replace OWN_RELIGION_CHILD_RECLASS = . if (OWN_RELIGION_CHILD_RECLASS == -1)
replace EITHER_INTERNET_ADJUSTED = . if (EITHER_INTERNET_ADJUSTED == -1)
replace POTENTIAL_PARTNER_GENDER_RECODES = . if (POTENTIAL_PARTNER_GENDER_RECODES == -1)
replace ALT_PARTNER_GENDER = . if (ALT_PARTNER_GENDER == -1)
replace RESPONDENT_RELIGION_AT_16 = . if (RESPONDENT_RELIGION_AT_16 == -1)
replace PARTNER_RELIGION_AT_16 = . if (PARTNER_RELIGION_AT_16 == -1)
replace HOME_COUNTRY_RECODE = . if (HOME_COUNTRY_RECODE == -1)
replace PP2_PPHHHEAD = . if (PP2_PPHHHEAD == -1 | PP2_PPHHHEAD == -2)
replace PP2_PPHHSIZE = . if (PP2_PPHHSIZE == -1 | PP2_PPHHSIZE == -2)
replace PP2_PPHOUSE = . if (PP2_PPHOUSE == -1 | PP2_PPHOUSE == -2)
replace PP2_PPINCIMP = . if (PP2_PPINCIMP == -1 | PP2_PPINCIMP == -2)
replace PP2_PPMARIT = . if (PP2_PPMARIT == -1 | PP2_PPMARIT == -2)
replace PP2_PPMSACAT = . if (PP2_PPMSACAT == -1 | PP2_PPMSACAT == -2)
replace PP2_PPEDUC = . if (PP2_PPEDUC == -1 | PP2_PPEDUC == -2)
replace PP2_PPEDUCAT = . if (PP2_PPEDUCAT == -1 | PP2_PPEDUCAT == -2)
replace PP2_PPETHM = . if (PP2_PPETHM == -1 | PP2_PPETHM == -2)
replace PP2_PPREG4 = . if (PP2_PPREG4 == -1 | PP2_PPREG4 == -2)
replace PP2_PPRENT = . if (PP2_PPRENT == -1 | PP2_PPRENT == -2)
replace PP2_PPT01 = . if (PP2_PPT01 == -1 | PP2_PPT01 == -2)
replace PP2_PPT1317 = . if (PP2_PPT1317 == -1 | PP2_PPT1317 == -2)
replace PP2_PPT18OV = . if (PP2_PPT18OV == -1 | PP2_PPT18OV == -2)
replace PP2_PPT25 = . if (PP2_PPT25 == -1 | PP2_PPT25 == -2)
replace PP2_PPT612 = . if (PP2_PPT612 == -1 | PP2_PPT612 == -2)
replace PP2_PPWORK = . if (PP2_PPWORK == -1 | PP2_PPWORK == -2)
replace W2_Q1 = . if (W2_Q1 == -1)
replace W2_Q2 = . if (W2_Q2 == -1)
replace W2_Q3 = . if (W2_Q3 == -1)
replace W2_Q4 = . if (W2_Q4 == -1)
replace W2_Q5 = . if (W2_Q5 == -1)
replace W2_Q6 = . if (W2_Q6 == -1)
replace W2_Q7 = . if (W2_Q7 == -1)
replace W2_Q8 = . if (W2_Q8 == -1)
replace W2_Q9 = . if (W2_Q9 == -1)
replace W2_Q10 = . if (W2_Q10 == -1)
replace PP3_PPHHHEAD = . if (PP3_PPHHHEAD == -1 | PP3_PPHHHEAD == -2)
replace PP3_PPHHSIZE = . if (PP3_PPHHSIZE == -1 | PP3_PPHHSIZE == -2)
replace PP3_PPHOUSE = . if (PP3_PPHOUSE == -1 | PP3_PPHOUSE == -2)
replace PP3_PPINCIMP = . if (PP3_PPINCIMP == -1 | PP3_PPINCIMP == -2)
replace PP3_PPMARIT = . if (PP3_PPMARIT == -1 | PP3_PPMARIT == -2)
replace PP3_PPMSACAT = . if (PP3_PPMSACAT == -1 | PP3_PPMSACAT == -2)
replace PP3_PPRENT = . if (PP3_PPRENT == -1 | PP3_PPRENT == -2)
replace PP3_PPREG4 = . if (PP3_PPREG4 == -1 | PP3_PPREG4 == -2)
replace PP3_PPT01 = . if (PP3_PPT01 == -1 | PP3_PPT01 == -2)
replace PP3_PPT1317 = . if (PP3_PPT1317 == -1 | PP3_PPT1317 == -2)
replace PP3_PPT18OV = . if (PP3_PPT18OV == -1 | PP3_PPT18OV == -2)
replace PP3_PPT25 = . if (PP3_PPT25 == -1 | PP3_PPT25 == -2)
replace PP3_PPT612 = . if (PP3_PPT612 == -1 | PP3_PPT612 == -2)
replace PP3_PPWORK = . if (PP3_PPWORK == -1 | PP3_PPWORK == -2)
replace PP3_PPEDUC = . if (PP3_PPEDUC == -1 | PP3_PPEDUC == -2)
replace PP3_PPEDUCAT = . if (PP3_PPEDUCAT == -1 | PP3_PPEDUCAT == -2)
replace PP3_PPETHM = . if (PP3_PPETHM == -1 | PP3_PPETHM == -2)
replace W3_Q1 = . if (W3_Q1 == -1)
replace W3_Q2 = . if (W3_Q2 == -1)
replace W3_Q3 = . if (W3_Q3 == -1)
replace W3_Q4 = . if (W3_Q4 == -1)
replace W3_MBTIMING_YEAR = . if (W3_MBTIMING_YEAR == -1)
replace W3_Q5 = . if (W3_Q5 == -1)
replace W3_Q6 = . if (W3_Q6 == -1)
replace W3_Q7 = . if (W3_Q7 == -1)
replace W3_Q8 = . if (W3_Q8 == -1)
replace W3_Q9 = . if (W3_Q9 == -1)
replace W3_Q10 = . if (W3_Q10 == -1)
replace W3_NONMBTIMING_YEAR = . if (W3_NONMBTIMING_YEAR == -1)
replace Q15A1 = . if (Q15A1 == -1)
replace W4_Q1 = . if (W4_Q1 == -1)
replace W4_Q2 = . if (W4_Q2 == -1)
replace W4_QUALITY = . if (W4_QUALITY == -1)
replace W4_ATTRACTIVE = . if (W4_ATTRACTIVE == -1)
replace W4_ATTRACTIVE_PARTNER = . if (W4_ATTRACTIVE_PARTNER == -1)
replace W4_Q3 = . if (W4_Q3 == -1)
replace W4_Q4 = . if (W4_Q4 == -1)
replace W4_Q7 = . if (W4_Q7 == -1)
replace W4_Q8_A = . if (W4_Q8_A == -1)
replace W4_Q8_B = . if (W4_Q8_B == -1)
replace W4_Q9 = . if (W4_Q9 == -1)
replace W4_Q10 = . if (W4_Q10 == -1)
replace PP4_PPEDUC = . if (PP4_PPEDUC == -1 | PP4_PPEDUC == -2)
replace PP4_PPEDUCAT = . if (PP4_PPEDUCAT == -1 | PP4_PPEDUCAT == -2)
replace PP4_PPETHM = . if (PP4_PPETHM == -1 | PP4_PPETHM == -2)
replace PP4_PPHHHEAD = . if (PP4_PPHHHEAD == -1 | PP4_PPHHHEAD == -2)
replace PP4_PPHHSIZE = . if (PP4_PPHHSIZE == -1 | PP4_PPHHSIZE == -2)
replace PP4_PPHOUSE = . if (PP4_PPHOUSE == -1 | PP4_PPHOUSE == -2)
replace PP4_PPINCIMP = . if (PP4_PPINCIMP == -1 | PP4_PPINCIMP == -2)
replace PP4_PPMARIT = . if (PP4_PPMARIT == -1 | PP4_PPMARIT == -2)
replace PP4_PPMSACAT = . if (PP4_PPMSACAT == -1 | PP4_PPMSACAT == -2)
replace PP4_PPREG4 = . if (PP4_PPREG4 == -1 | PP4_PPREG4 == -2)
replace PP4_PPRENT = . if (PP4_PPRENT == -1 | PP4_PPRENT == -2)
replace PP4_PPT01 = . if (PP4_PPT01 == -1 | PP4_PPT01 == -2)
replace PP4_PPT25 = . if (PP4_PPT25 == -1 | PP4_PPT25 == -2)
replace PP4_PPT612 = . if (PP4_PPT612 == -1 | PP4_PPT612 == -2)
replace PP4_PPT1317 = . if (PP4_PPT1317 == -1 | PP4_PPT1317 == -2)
replace PP4_PPT18OV = . if (PP4_PPT18OV == -1 | PP4_PPT18OV == -2)
replace PP4_PPWORK = . if (PP4_PPWORK == -1 | PP4_PPWORK == -2)
replace PPA2009_HOW_OFTEN_SERVICES = . if (PPA2009_HOW_OFTEN_SERVICES == -1 | PPA2009_HOW_OFTEN_SERVICES == -2)
replace W5_Q1 = . if (W5_Q1 == -1)
replace W5_Q2 = . if (W5_Q2 == -1)
replace W5_SEX_FREQUENCY = . if (W5_SEX_FREQUENCY == -1)
replace W5_P_MONOGAMY = . if (W5_P_MONOGAMY == -1)
replace W5_IDENTITY = . if (W5_IDENTITY == -1)
replace W5_OUTNESS = . if (W5_OUTNESS == -1)
replace W5_Q3 = . if (W5_Q3 == -1)
replace W5_Q4 = . if (W5_Q4 == -1)
replace W5_MBTIMING_MONTH = . if (W5_MBTIMING_MONTH == -1)
replace W5_Q5 = . if (W5_Q5 == -1)
replace W5_Q6 = . if (W5_Q6 == -1)
replace W5_Q7 = . if (W5_Q7 == -1)
replace W5_MAR_MONTH = . if (W5_MAR_MONTH == -1)
replace W5_Q8 = . if (W5_Q8 == -1)
replace W5_CIV_YEAR = . if (W5_CIV_YEAR == -1)
replace W5_CIV_MONTH = . if (W5_CIV_MONTH == -1)
replace W5_Q9 = . if (W5_Q9 == -1)
replace W5_Q10 = . if (W5_Q10 == -1)
replace W5_NONMBTIMING_MONTH = . if (W5_NONMBTIMING_MONTH == -1)
replace PP5_PPAGE = . if (PP5_PPAGE == -2 | PP5_PPAGE == -1)
replace PP5_PPEDUC = . if (PP5_PPEDUC == -2 | PP5_PPEDUC == -1)
replace PP5_PPEDUCAT = . if (PP5_PPEDUCAT == -2 | PP5_PPEDUCAT == -1)
replace PP5_PPETHM = . if (PP5_PPETHM == -2 | PP5_PPETHM == -1)
replace PP5_PPGENDER = . if (PP5_PPGENDER == -2 | PP5_PPGENDER == -1)
replace PP5_PPHHSIZE = . if (PP5_PPHHSIZE == -2 | PP5_PPHHSIZE == -1)
replace PP5_PPHOUSE = . if (PP5_PPHOUSE == -2 | PP5_PPHOUSE == -1)
replace PP5_PPINCIMP = . if (PP5_PPINCIMP == -2 | PP5_PPINCIMP == -1)
replace PP5_PPMARIT = . if (PP5_PPMARIT == -2 | PP5_PPMARIT == -1)
replace PP5_PPREG4 = . if (PP5_PPREG4 == -2 | PP5_PPREG4 == -1)
replace PP5_PPT01 = . if (PP5_PPT01 == -2 | PP5_PPT01 == -1)
replace PP5_PPT612 = . if (PP5_PPT612 == -2 | PP5_PPT612 == -1)
replace PP5_PPT1317 = . if (PP5_PPT1317 == -2 | PP5_PPT1317 == -1)
replace PP5_PPT18OV = . if (PP5_PPT18OV == -2 | PP5_PPT18OV == -1)
replace PP5_PPWORK = . if (PP5_PPWORK == -2 | PP5_PPWORK == -1)
replace PPMARIT_2014 = . if (PPMARIT_2014 == -2 | PPMARIT_2014 == -1)
replace PPMARIT_2013 = . if (PPMARIT_2013 == -2 | PPMARIT_2013 == -1)
replace PPMARIT_2012 = . if (PPMARIT_2012 == -2 | PPMARIT_2012 == -1)
replace PPMARIT_2011 = . if (PPMARIT_2011 == -2 | PPMARIT_2011 == -1)
replace PPMARIT_2010 = . if (PPMARIT_2010 == -2 | PPMARIT_2010 == -1)
replace PPMARIT_2009 = . if (PPMARIT_2009 == -2 | PPMARIT_2009 == -1)
replace PPMARIT_2007 = . if (PPMARIT_2007 == -2 | PPMARIT_2007 == -1)


